// ╔══════════════════════════════════════════════════════════════╗
// ║  SKICA – Bridge (callback registry pro cyklické závislosti) ║
// ╚══════════════════════════════════════════════════════════════╝

/** @type {import('./types.js').Bridge} */
export const bridge = {
  updateMobileCancelBtn: null,
  updateMobileCoords: null,
  updatePolylineButtons: null,
  updateTraceButtons: null,
  updateHolderDrawButtons: null,
  confirmHolderDraw: null,
  cancelHolderDraw: null,
  toggleHolderDrawSide: null,
  refreshCamToolGeometry: null,
  getCamToolGeometry: null,
  applyCamToolGeometry: null,
  finishProfileTrace: null,
  finishChainDimension: null,
  updateProperties: null,
  updateObjectList: null,
  updateIntersectionList: null,
  calculateAllIntersections: null,
  runCncExport: null,
  // Absolutní world (x,y) → G-kód adresa (osy/jednotky dle machineType +
  // xDisplayMode) – sdílená s runCncExport(), aby se konvence os nerozjela
  // na dvou místech (viz numericalInput.js – ruční zápis G-kódu).
  formatAbsCoord: null,
  renderCncCodeToCanvas: null,
  renderVkPreview: null,
  fitVkPreviewView: null,
  renderNumPreview: null,
  commitVkToDrawing: null,
  vkDrawPoint: null,
  vkDrawUndo: null,
  updateVkDrawButton: null,
  setTool: null,
  renderAll: null,
  resetHint: null,
  measureSelection: null,
  tangentFromSelection: null,
  offsetFromSelection: null,
  trimFromSelection: null,
  extendFromSelection: null,
  filletFromSelection: null,
  chamferFromSelection: null,
  threadFromSelection: null,
  perpFromSelection: null,
  horizontalFromSelection: null,
  parallelFromSelection: null,
  centerMarkFromSelection: null,
  scaleFromSelection: null,
  filletChamferFromSelection: null,
  mirrorFromSelection: null,
  rotateFromSelection: null,
  linearArrayFromSelection: null,
  circularArrayFromSelection: null,
  copyPlaceFromSelection: null,
  saveProject: null,
  showFileDialog: null,
  showLibraryDialog: null,
  showProjectsDialog: null,
};
